### ISSUE TITLE
Add instructions for getting started

### ISSUE THREAD

**Issue by saqibur** [ShaonMahmood/ProjectCreationAutomation#1]
We can add some instructions to get up and running with the project for newcomers. For instance, we can add this to `README.md`:

> ## Getting Started
> 1. Clone the project: `git clone https://github.com/ShaonMahmood/ProjectCreationAutomation`
> 2. Create a virtual environment: `virtualenv venv`
> 3. Install dependencies: `pip install -r requirements.txt`
> 4. Run: `python3 automation_gui.py`

I can create a pull request to add these lines in if you wish.

**Comment by ShaonMahmood** [comment]
Sure

**Comment by saqibur** [comment]
Thank you for merging. We can close this issue now.
